version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vanetlab-be:/app
      - ./vanetlab-ns3:/vlns3
    command: bash
    network_mode: "host"
    ports:
      - "5000:5000"
    env_file:
      - .env
